# extractors/prompts/combiner_prompt.py


def build_combiner_prompt(
    vision_raw: dict,
    text_raw: dict,
    anchor_gt: dict,
    known_fabric_ids: set[str],
    expected_aesthetic: str = "",
) -> str:
    """
    Prompt for the text LLM that merges vision output + text extraction
    into the final unified output dict.

    This model's job is reconciliation, not discovery.
    It should trust the anchor_gt above all else.
    """

    import json

    anchor_summary = []
    if anchor_gt.get("fabric_map"):
        anchor_summary.append(f"Fabrics: {anchor_gt['fabric_map']}")
    if anchor_gt.get("techniques"):
        anchor_summary.append(f"Techniques: {anchor_gt['techniques']}")
    if anchor_gt.get("color_name"):
        anchor_summary.append(f"Color: {anchor_gt['color_name']}")

    unknown_fabric_warning = ""
    if anchor_gt.get("unknown_fabrics"):
        names = ", ".join(f'"{f}"' for f in anchor_gt["unknown_fabrics"])
        unknown_fabric_warning = f"""
CANDIDATE FORCING — MANDATORY:
The following fabrics were confirmed by the brand but have NO entry in our database:
  {names}
These MUST appear in new_fabric_candidates[].
If vision_output placed them in fabric_vocabulary.confirmed[], remove them from there
and move them to new_fabric_candidates[] with source = "brand_confirmed_unknown".
This is not optional.
"""

    return f"""You are assembling a final garment intelligence record.
You have two input sources: a vision model output and a text extraction output.
Your job is to reconcile them into a single authoritative output, following the rules below.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GROUND TRUTH (highest authority — overrides both sources)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{chr(10).join(anchor_summary)}

{unknown_fabric_warning}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECONCILIATION RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FABRICS:
1. fabric_vocabulary.confirmed[] must contain ONLY fabric names that
   (a) appear in GROUND TRUTH and (b) have a matching fabric_id in the database.
2. Any fabric in GROUND TRUTH that has no database match → new_fabric_candidates[].
3. Any fabric invented by vision model that contradicts GROUND TRUTH → discard silently.
4. vision_only[] enriches confirmed entries with visual observations — keep these.

6. TECHNIQUES:
1. techniques.confirmed[] must match GROUND TRUTH techniques exactly.
2. If vision model identified a technique NOT in GROUND TRUTH, move it to vision_only[] with confidence = "uncertain" — never add it to confirmed[].
3. If mirror work is present, you MUST output a key "mirror_scatter_pattern" inside the techniques dictionary. If vision returned "jaal" but the visual evidence shows irregular scatter, correct it to "constellation".

COLOR:
1. If GROUND TRUTH has color_name, use only that. Set color_palette to [null]
   and note "resolved via controlled lookup".
2. Do not accept hex values generated by the vision model — they hallucinate.
3. Create a top-level "colour_intelligence" block containing "season_wearability"
   (pulled from drape_behavior's seasonal_read), "color_name", and "family"
   (from color_harmony).

GARMENT STRUCTURE:
1. components[] must list all pieces visible in image AND match component count
   from GROUND TRUTH if available.
2. garment_type must be specific — see allowed vocabulary in vision output.
   "sherwani" alone is rejected. Use "3-piece-sherwani-set" or "achkan-jacket-set".
3. embroidery_density: prefer "all-over" when both front and back are covered.

SILHOUETTE:
1. Must be from the allowed vocabulary — not a freeform description.
2. Ensure the silhouette matches the observed garment structure.

AESTHETIC:
1. aesthetic_category MUST be exactly this string if provided: "{expected_aesthetic}"
2. If the string is empty, synthesize a category based on the visual evidence.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INPUT: VISION OUTPUT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{json.dumps(vision_raw, indent=2, default=str)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INPUT: TEXT EXTRACTION OUTPUT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{json.dumps(text_raw, indent=2, default=str)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Return a single JSON object. No markdown. No preamble. Start with {{ end with }}.

Required top-level keys:
  fabric_vocabulary, techniques, embroidery_density, drape_behavior, surface_texture,
  weight_estimate, silhouette, color_palette, color_harmony, colour_intelligence,
  visual_weight, motif_vocabulary, components, gender, garment_type, matched_construction_id,
  outfit_completeness, styling_dna, occasion_suitability, styling_observations,
  aesthetic_category, aesthetic_justification, new_fabric_candidates,
  new_embellishment_candidates, new_pattern_candidates, needs_manual_review,
  confidence_notes

needs_manual_review must be true if new_fabric_candidates is non-empty.
"""
